### ISSUE TITLE
Does support self-hosted runner?

### ISSUE THREAD

**Issue by wood0203** [417-72KI/danger-swiftlint#60]
Hi, I'm trying to run this docker github action in self-hosted runner.
i have private repository with my organization and i'm using macOS
here is my workflow file.
```YAML

name: Danger SwiftLint

on:
  pull_request:

jobs:
  Danger:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

the error was
`Container action is only supported on Linux`

i also tried to run image in local using statement posted in your docker hub.
`docker run -v pwd:pwd -w pwd 41772ki/danger-swiftlint local`

but it did not comment on my PR.
maybe because of running danger in local not comment on PR,
i saw it in danger swift documentation.

Would you please do me a favor?
